### ISSUE TITLE
Please update your Google Analytics code

### ISSUE THREAD

**Issue by apreshill** [YTLogos/TaoYan#12]
Hi there Tao 👋 

I love your website! And thanks for the attribution. Could you update your Google Analytics code (https://github.com/YTLogos/TaoYan/blob/3776780f1caa635963f92655f25ec64db2ab463c/config/_default/params.toml#L269)? You are currently using mine so your posts are tracking on my website. Thank you!

Alison

**Comment by YTLogos** [comment]
Sorry @apreshill for the later response. I just updated that, so it should be solved once the build goes through.
